// ==UserScript==
// @name         🏦 ACB | Xuất Excel | Tự tải đủ 12 tháng
// @namespace    acb-auto-export
// @version      1.3.2
// @description  Tự động chọn từng tháng và tải Excel trên ACB ONE BIZ; tô màu thành phần tự động, chọn ô đăng nhập/mật khẩu, kích hoạt 2 ô bằng điền 1 rồi xóa, kiểm tra nút tải, dừng và hot-load chống cache
// @match        https://*.acb.com.vn/*
// @grant        none
// @run-at       document-idle
// @updateURL    https://raw.githubusercontent.com/datphuho88-dev/tampermonkey-scripts/main/%F0%9F%8F%A6%20ACB%20-%20Xu%E1%BA%A5t%20Excel%20-%20T%E1%BB%B1%20t%E1%BA%A3i%20%C4%91%E1%BB%A7%2012%20th%C3%A1ng.user.js
// @downloadURL  https://raw.githubusercontent.com/datphuho88-dev/tampermonkey-scripts/main/%F0%9F%8F%A6%20ACB%20-%20Xu%E1%BA%A5t%20Excel%20-%20T%E1%BB%B1%20t%E1%BA%A3i%20%C4%91%E1%BB%A7%2012%20th%C3%A1ng.user.js
// ==/UserScript==

(function(){
'use strict';
const V='1.3.2';
const API='https://api.github.com/repos/datphuho88-dev/tampermonkey-scripts/contents/%F0%9F%8F%A6%20ACB%20-%20Xu%E1%BA%A5t%20Excel%20-%20T%E1%BB%B1%20t%E1%BA%A3i%20%C4%91%E1%BB%A7%2012%20th%C3%A1ng.user.js';
const IK='__ACB_AUTO_EXPORT_INSTANCE__',PID='acb-auto-export-panel',PK='ACB_AUTO_EXPORT_PANEL_POS',UK='ACB_AUTO_LOGIN_USER_SELECTOR',WK='ACB_AUTO_LOGIN_PASS_SELECTOR';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let running=false,stopRequested=false,initTimer=null,captureCleanup=null,highlightTimer=null;
const marked=new Map();
try{window[IK]?.destroy?.();}catch{}
const norm=s=>(s||'').replace(/\s+/g,' ').trim().toLowerCase();
const visible=el=>{if(!el)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};
const usable=el=>!!el&&visible(el)&&!el.disabled&&el.getAttribute('aria-disabled')!=='true'&&getComputedStyle(el).pointerEvents!=='none';
function status(t,type='info'){const e=document.querySelector('#acb-auto-status');if(!e)return;e.textContent=t;e.style.color=({info:'#374151',success:'#15803d',warning:'#b45309',error:'#dc2626'})[type]||'#374151'}
async function latest(){const r=await fetch(API+'?ref=main&_='+Date.now(),{cache:'no-store',credentials:'omit',headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw Error('GitHub API HTTP '+r.status);const d=await r.json();const b=String(d.content||'').replace(/\s/g,'');if(!b)throw Error('Không đọc được code GitHub');return new TextDecoder().decode(Uint8Array.from(atob(b),c=>c.charCodeAt(0)))}
async function hotReload(){if(running)return status('Hãy dừng tiến trình trước khi LOAD','warning');status('Đang lấy code mới nhất...');try{const s=await latest(),m=s.match(/\/\/\s*@version\s+([^\s]+)/),code=s.replace(/\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/,'');status('Đã lấy v'+(m?.[1]||'?')+' • đang chạy...','success');setTimeout(()=>{try{new Function(code)()}catch(e){console.error(e);alert('ACB LOAD lỗi: '+e.message)}},30)}catch(e){console.error(e);status('LOAD thất bại: '+e.message,'error')}}
function esc(v){return window.CSS?.escape?CSS.escape(String(v)):String(v).replace(/([ !"#$%&'()*+,./:;<=>?@[\\\]^`{|}~])/g,'\\$1')}
function selector(el){if(!(el instanceof Element))return null;if(el.id)return'#'+esc(el.id);const tag=el.tagName.toLowerCase(),name=el.getAttribute('name');if(name){const q=`${tag}[name="${String(name).replace(/"/g,'\\"')}"]`;if(document.querySelectorAll(q).length===1)return q}const type=el.getAttribute('type');if(tag==='input'&&type){const q=`input[type="${esc(type)}"]`;if([...document.querySelectorAll(q)].filter(visible).length===1)return q}const a=[];let c=el;for(let d=0;c&&c!==document.body&&d<5;d++,c=c.parentElement){let p=c.tagName.toLowerCase();if(c.id){a.unshift('#'+esc(c.id));break}const sib=c.parentElement?[...c.parentElement.children].filter(x=>x.tagName===c.tagName):[];if(sib.length>1)p+=`:nth-of-type(${sib.indexOf(c)+1})`;a.unshift(p)}return a.join(' > ')}
function saved(k){const q=localStorage.getItem(k);if(!q)return null;try{return document.querySelector(q)}catch{return null}}
function flash(el,color){if(!el)return false;const o=el.style.outline,oo=el.style.outlineOffset;el.style.outline=`4px solid ${color}`;el.style.outlineOffset='2px';try{el.scrollIntoView({block:'center',inline:'nearest',behavior:'smooth'})}catch{}setTimeout(()=>{el.style.outline=o;el.style.outlineOffset=oo},2200);return true}
function mark(el,color,label){if(!el||!visible(el))return false;if(!marked.has(el))marked.set(el,{outline:el.style.outline,offset:el.style.outlineOffset,shadow:el.style.boxShadow});el.style.outline=`2px solid ${color}`;el.style.outlineOffset='2px';el.style.boxShadow=`0 0 0 2px ${color}22`;el.dataset.acbAutoMarked=label;return true}
function clearMarks(){for(const[el,o]of marked){if(el?.isConnected){el.style.outline=o.outline;el.style.outlineOffset=o.offset;el.style.boxShadow=o.shadow;delete el.dataset.acbAutoMarked}}marked.clear()}
function findByLabel(txt){const w=norm(txt);for(const e of document.querySelectorAll('td,div,span,label,p')){const t=norm(e.innerText);if(t!==w&&!t.startsWith(w+' ')&&!t.startsWith(w+':'))continue;const own=e.querySelector('select');if(own&&visible(own))return own;let p=e.parentElement;for(let i=0;p&&i<4;i++,p=p.parentElement){const s=[...p.querySelectorAll('select')].find(visible);if(s)return s}}return null}
function findMonth(){for(const s of document.querySelectorAll('select')){if(!visible(s))continue;const o=[...s.options].map(x=>x.text.trim());let n=0;for(let m=1;m<=12;m++)if(o.includes(String(m).padStart(2,'0')))n++;if(n>=10)return s}return findByLabel('Tháng')}
function findYear(){for(const s of document.querySelectorAll('select')){if(!visible(s))continue;if([...s.options].filter(o=>/^20\d{2}$/.test(o.text.trim())).length>=2)return s}return findByLabel('Năm')}
function findExport(){const c=[...document.querySelectorAll('input[type="button"],input[type="submit"],button,a')].filter(e=>{if(!usable(e))return false;const t=norm(e.innerText||e.value||e.title);return t.includes('xuất excel')||t.includes('xuat excel')});if(!c.length)return null;return c.length===1?c[0]:c.sort((a,b)=>b.getBoundingClientRect().left-a.getBoundingClientRect().left)[0]}
function applyHighlights(){for(const[e]of[...marked])if(!e?.isConnected)marked.delete(e);let n=0;if(mark(saved(UK),'#2563eb','Tên đăng nhập'))n++;if(mark(saved(WK),'#7c3aed','Mật khẩu'))n++;if(mark(findMonth(),'#0284c7','Tháng'))n++;if(mark(findYear(),'#16a34a','Năm'))n++;if(mark(findExport(),'#dc2626','Xuất Excel'))n++;return n}
function capture(kind){captureCleanup?.();const isUser=kind==='user',key=isUser?UK:WK,label=isUser?'TÊN ĐĂNG NHẬP':'MẬT KHẨU';status('Bấm trực tiếp vào ô '+label+'...','warning');let h=null,old='',off='';const clear=()=>{if(h){h.style.outline=old;h.style.outlineOffset=off;h=null}};const move=e=>{const t=e.target.closest?.('input,textarea,[contenteditable="true"]');if(!t||t.closest('#'+PID)||t===h)return;clear();h=t;old=t.style.outline;off=t.style.outlineOffset;t.style.outline='4px solid #f59e0b';t.style.outlineOffset='2px'};const click=e=>{const t=e.target.closest?.('input,textarea,[contenteditable="true"]');if(!t||t.closest('#'+PID))return;e.preventDefault();e.stopPropagation();const q=selector(t);if(!q){status('Không tạo được selector','error');return cleanup()}localStorage.setItem(key,q);status('Đã lưu ô '+label,'success');flash(t,isUser?'#2563eb':'#7c3aed');cleanup();setTimeout(applyHighlights,60)};const keydown=e=>{if(e.key==='Escape'){status('Đã hủy chọn','warning');cleanup()}};function cleanup(){clear();document.removeEventListener('mousemove',move,true);document.removeEventListener('click',click,true);document.removeEventListener('keydown',keydown,true);if(captureCleanup===cleanup)captureCleanup=null}captureCleanup=cleanup;setTimeout(()=>{document.addEventListener('mousemove',move,true);document.addEventListener('click',click,true);document.addEventListener('keydown',keydown,true)},120)}
function testLogin(){let n=0;if(flash(saved(UK),'#2563eb'))n++;if(flash(saved(WK),'#7c3aed'))n++;status(`Kiểm tra đăng nhập: ${n}/2`,n===2?'success':'warning')}
function setField(el,v){if(!el)return;if(el instanceof HTMLInputElement){const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;s?s.call(el,v):el.value=v}else if(el instanceof HTMLTextAreaElement){const s=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;s?s.call(el,v):el.value=v}else if(el.isContentEditable)el.textContent=v;else return;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}
async function touch(){const u=saved(UK),p=saved(WK);if(!u||!p)return status('Chưa chọn đủ 2 ô','error');for(const[e,l]of[[u,'TÊN ĐĂNG NHẬP'],[p,'MẬT KHẨU']]){if(!visible(e))return status('Không thấy ô '+l,'error');try{e.focus()}catch{}status('Điền 1 vào '+l+'...');setField(e,'1');await sleep(350);status('Xóa '+l+'...');setField(e,'');await sleep(250)}try{p.focus()}catch{}status('Đã điền 1 rồi xóa ở cả 2 ô','success')}
function verify(show=false){const b=findExport();if(!b){status('Nút XUẤT EXCEL chưa sẵn sàng','error');if(show)alert('Không tìm thấy nút XUẤT EXCEL đang sẵn sàng.');return false}flash(b,'#16a34a');status('Nút XUẤT EXCEL sẵn sàng','success');return true}
function testElements(){let n=0;if(flash(findMonth(),'#2563eb'))n++;if(flash(findYear(),'#16a34a'))n++;if(flash(findExport(),'#dc2626'))n++;status(`Kiểm tra thành phần: ${n}/3`,n===3?'success':'warning')}
function setSelect(s,v){if(!s)return false;const w=String(v),p=/^\d+$/.test(w)?w.padStart(2,'0'):w,o=[...s.options].find(x=>x.value===w||x.text.trim()===w||x.value===p||x.text.trim()===p);if(!o)return false;s.value=o.value;s.dispatchEvent(new Event('input',{bubbles:true}));s.dispatchEvent(new Event('change',{bubbles:true}));return true}
async function waitExport(ms=8000){const t=Date.now();while(Date.now()-t<ms){const b=findExport();if(usable(b))return b;await sleep(150)}return null}
function buttons(){const s=document.querySelector('#acb-auto-start'),x=document.querySelector('#acb-auto-stop');if(s){s.disabled=running;s.style.opacity=running?'.55':'1'}if(x){x.disabled=!running;x.style.opacity=running?'1':'.45'}}
function stop(){if(!running)return;stopRequested=true;status('Đang dừng sau bước hiện tại...','warning')}
async function start(){if(running)return;const m=findMonth(),y=findYear(),e=findExport();if(!m)return alert('Không tìm thấy ô chọn THÁNG.');if(!y)return alert('Không tìm thấy ô chọn NĂM.');if(!e)return alert('Không tìm thấy nút XUẤT EXCEL đang sẵn sàng.');const cy=[...y.options].find(o=>o.value===y.value)?.text.trim()||new Date().getFullYear(),yr=prompt('Nhập năm cần tải đủ 12 tháng:',cy);if(!yr)return;if(![...y.options].some(o=>o.text.trim()===String(yr)||o.value===String(yr)))return alert('Không tìm thấy năm '+yr+'.');if(!confirm(`Sẽ tải Excel từ tháng 01 đến tháng 12 năm ${yr}.\n\nTiếp tục?`))return;running=true;stopRequested=false;buttons();try{status('Đang chọn năm '+yr+'...');setSelect(y,yr);await sleep(700);let done=0;for(let i=1;i<=12&&!stopRequested;i++){const mm=String(i).padStart(2,'0');status(`Đang tải ${mm}/${yr} • ${i}/12`);if(!(setSelect(m,mm)||setSelect(m,i)))continue;await sleep(900);if(stopRequested)break;const b=await waitExport();if(!b)throw Error('Nút Xuất Excel chưa sẵn sàng tại tháng '+mm);if(!usable(b))throw Error('Nút Xuất Excel bị khóa tại tháng '+mm);b.click();done++;await sleep(3000)}status(stopRequested?'Đã dừng':`Hoàn tất ${done}/12 tháng năm ${yr}`,stopRequested?'warning':'success')}catch(err){console.error(err);status('Lỗi: '+err.message,'error');alert('Có lỗi:\n'+err.message)}finally{running=false;stopRequested=false;buttons()}}
function btn(text,id,bg,fn){const b=document.createElement('button');b.id=id;b.type='button';b.textContent=text;b.style.cssText=`border:0;border-radius:7px;padding:7px 10px;cursor:pointer;background:${bg};color:#fff;font-size:12px;font-weight:700;white-space:nowrap`;b.addEventListener('click',fn);return b}
function pos(p){try{const x=JSON.parse(localStorage.getItem(PK)||'null');if(!x)return;const ml=Math.max(0,innerWidth-p.offsetWidth),mt=Math.max(0,innerHeight-45);p.style.left=Math.min(Math.max(0,x.left),ml)+'px';p.style.top=Math.min(Math.max(0,x.top),mt)+'px';p.style.right='auto';p.style.bottom='auto'}catch{}}
function drag(p,h){h.style.cursor='move';h.addEventListener('mousedown',e=>{if(e.button!==0||e.target.closest('button'))return;e.preventDefault();const r=p.getBoundingClientRect(),sx=e.clientX,sy=e.clientY,sl=r.left,st=r.top;p.style.left=sl+'px';p.style.top=st+'px';p.style.right='auto';p.style.bottom='auto';const mv=v=>{p.style.left=Math.min(Math.max(0,sl+v.clientX-sx),Math.max(0,innerWidth-p.offsetWidth))+'px';p.style.top=Math.min(Math.max(0,st+v.clientY-sy),Math.max(0,innerHeight-45))+'px'};const up=()=>{document.removeEventListener('mousemove',mv);document.removeEventListener('mouseup',up);const q=p.getBoundingClientRect();localStorage.setItem(PK,JSON.stringify({left:Math.round(q.left),top:Math.round(q.top)}))};document.addEventListener('mousemove',mv);document.addEventListener('mouseup',up)})}
function panel(){document.querySelector('#'+PID)?.remove();const p=document.createElement('div');p.id=PID;p.style.cssText='position:fixed;right:18px;bottom:18px;z-index:2147483647;width:310px;padding:10px;background:#fff;border:1px solid #cbd5e1;border-radius:10px;box-shadow:0 5px 18px rgba(0,0,0,.25);font-family:Arial,sans-serif;color:#111827;user-select:none';const h=document.createElement('div');h.style.cssText='display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px';const t=document.createElement('div');t.innerHTML=`<b>🏦 ACB Auto Excel</b> <span style="font-size:10px;background:#eef2ff;color:#3730a3;padding:2px 5px;border-radius:8px">v${V}</span>`;h.append(t,btn('↻ LOAD','acb-auto-load','#0f766e',hotReload));const pick=document.createElement('div');pick.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-bottom:6px';pick.append(btn('👤 Chọn tên đăng nhập','acb-auto-pick-user','#2563eb',()=>capture('user')),btn('🔑 Chọn mật khẩu','acb-auto-pick-pass','#7c3aed',()=>capture('pass')));const la=document.createElement('div');la.style.cssText='display:flex;gap:6px;margin-bottom:6px';const fill=btn('✏ Điền MK','acb-auto-touch-login','#c2410c',touch);fill.style.flex='1';la.append(fill);const a=document.createElement('div');a.style.cssText='display:flex;gap:6px;flex-wrap:wrap';a.append(btn('⬇ Tải đủ 12 tháng','acb-auto-start','#2868b2',start),btn('⏹ Dừng','acb-auto-stop','#dc2626',stop));const st=document.createElement('div');st.id='acb-auto-status';st.textContent='Sẵn sàng • v'+V;st.style.cssText='margin-top:8px;padding-top:7px;border-top:1px solid #e5e7eb;font-size:11px;font-weight:600';const help=document.createElement('div');help.textContent='Thành phần tìm thấy sẽ được tô viền tự động. Điền MK chỉ điền số 1 rồi xóa ở 2 ô đã chọn; không lưu mật khẩu.';help.style.cssText='margin-top:5px;font-size:10px;color:#6b7280;line-height:1.35';const tools=document.createElement('div');tools.style.cssText='display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin-top:7px;opacity:.42';const c1=btn('KT ô','acb-auto-check-login','#64748b',testLogin),c2=btn('KT TP','acb-auto-test','#64748b',testElements),c3=btn('KT tải','acb-auto-check-download','#64748b',()=>verify(true));for(const b of[c1,c2,c3]){b.style.padding='3px 5px';b.style.fontSize='9px';b.style.borderRadius='5px';b.style.fontWeight='600'}tools.append(c1,c2,c3);p.append(h,pick,la,a,st,help,tools);document.body.appendChild(p);pos(p);drag(p,h);buttons();applyHighlights();highlightTimer=setInterval(applyHighlights,1800)}
function destroy(){stopRequested=true;running=false;captureCleanup?.();if(initTimer)clearTimeout(initTimer);if(highlightTimer)clearInterval(highlightTimer);clearMarks();document.querySelector('#'+PID)?.remove()}
window[IK]={version:V,destroy,hotReload,testElements,testSavedLoginFields:testLogin,touchLoginFields:touch,applyDefaultHighlights:applyHighlights,verifyExportButton:verify};
initTimer=setTimeout(panel,300);
})();